// Classification after visually reviewing every owner-supplied photograph.
// Names on portraits come from filenames, not facial identification.
export const photoCatalog = [
  {
    id: "waiting-room-seating",
    file: "Amish chairs.jpg",
    category: "Waiting area",
    alt: "Wood-framed chairs and a brown sofa beside the waiting-room windows",
    placement: "Office tour",
  },
  {
    id: "building-close",
    file: "Arial Front close up.jpg",
    category: "Exterior",
    alt: "Front of the South Valley Family Dental building and covered entrance",
    placement: "Homepage location",
  },
  {
    id: "building-west",
    file: "Arial Front of building west.jpg",
    category: "Exterior",
    alt: "Elevated view of the dental office, parking area, and surrounding neighborhood",
    placement: "Office tour",
  },
  {
    id: "building-front",
    file: "Arial front building centered.jpg",
    category: "Exterior",
    alt: "Centered view of the dental office entrance from the parking area",
    placement: "Contact hero",
  },
  {
    id: "intraoral-xray",
    file: "BW xray.jpg",
    category: "Equipment",
    alt: "Wall-mounted dental X-ray arm beside a treatment-room window",
    placement: "Services equipment gallery",
  },
  {
    id: "bethany",
    file: "Bethany.jpg",
    category: "Portrait",
    alt: "Bethany, in an owner-supplied staff portrait",
    placement: "About, pending roster confirmation",
  },
  {
    id: "dental-instruments",
    file: "Dental tray 2.jpg",
    category: "Equipment",
    alt: "Dental instruments arranged on a treatment tray",
    placement: "Services equipment gallery",
  },
  {
    id: "dental-instruments-vertical",
    file: "Dental tray.jpg",
    category: "Equipment",
    alt: "Vertical view of a dental instrument tray and delivery unit",
    placement: "Alternate; landscape version selected",
  },
  {
    id: "massage-chair",
    file: "Massage Chair.jpg",
    category: "Office detail",
    alt: "Black massage chair in a room off the office hallway",
    placement: "Office tour; no availability claims",
  },
  {
    id: "treatment-room-door",
    file: "Opt 4 from door.jpg",
    category: "Treatment room",
    alt: "Dental chair, wood cabinetry, and windows viewed from a treatment-room doorway",
    placement: "Services hero",
  },
  {
    id: "treatment-room",
    file: "Opt 4.jpg",
    category: "Treatment room",
    alt: "Dental treatment room with a reclining chair, overhead light, and wood cabinets",
    placement: "Homepage and office tour",
  },
  {
    id: "paige",
    file: "Paige.jpg",
    category: "Portrait",
    alt: "Paige, in an owner-supplied staff portrait",
    placement: "About, pending roster confirmation",
  },
  {
    id: "panoramic-room",
    file: "Pano 2.jpg",
    category: "Equipment",
    alt: "Panoramic dental imaging unit viewed through its room doorway",
    placement: "Alternate; closer equipment view selected",
  },
  {
    id: "panoramic-xray",
    file: "Pano.jpg",
    category: "Equipment",
    alt: "Panoramic dental imaging unit inside the office",
    placement: "Services equipment gallery",
  },
  {
    id: "reception-workspace",
    file: "Reception back view.jpg",
    category: "Reception",
    alt: "Reception workspace with wood cabinetry, white counters, and the adjacent hallway",
    placement: "Office tour",
  },
  {
    id: "reception",
    file: "Reception front view.jpg",
    category: "Reception",
    alt: "Front reception counter with wood cabinetry and pendant lights",
    placement: "Office Info hero and patient resources",
  },
  {
    id: "richard",
    file: "Richard.jpg",
    category: "Portrait",
    alt: "Richard S. Johnson, DDS, wearing dark dental scrubs",
    placement: "Homepage and About biography",
  },
  {
    id: "valley-east",
    file: "SVFD East View Valley.jpg",
    category: "Local aerial",
    alt: "Aerial view across Providence toward the snow-dusted Cache Valley mountains",
    placement: "About local roots",
  },
  {
    id: "valley-southeast",
    file: "SVFD SE view valley.jpg",
    category: "Local aerial",
    alt: "Aerial neighborhood view with the South Valley Family Dental location labeled beneath the mountains",
    placement: "Contact location context",
  },
  {
    id: "valley-west",
    file: "SVFD West Valley.jpg",
    category: "Local aerial",
    alt: "Westward aerial view across Cache Valley with the dental office location labeled",
    placement: "Alternate; southeast view selected for directions",
  },
  {
    id: "team",
    file: "Staff photo.jpg",
    category: "Group portrait",
    alt: "South Valley Family Dental group photographed outside the office entrance",
    placement: "Homepage team introduction and About",
  },
  {
    id: "teresa",
    file: "Teresa.jpg",
    category: "Portrait",
    alt: "Teresa, in an owner-supplied staff portrait",
    placement: "About, pending roster confirmation",
  },
  {
    id: "waiting-room-wide",
    file: "Waiting room 2.jpg",
    category: "Waiting area",
    alt: "Waiting-room chairs beneath a wall map, with reception visible beyond",
    placement: "Office tour",
  },
  {
    id: "waiting-room-fireplace",
    file: "Waiting room fireplace.jpg",
    category: "Waiting area",
    alt: "Brown sofa and blue chairs arranged around the waiting-room fireplace",
    placement: "Homepage hero and office tour",
  },
  {
    id: "waiting-room-windows",
    file: "Waiting room windows.jpg",
    category: "Waiting area",
    alt: "Sunlit waiting area with a brown sofa, blue chairs, and plants beside a wall water feature",
    placement: "Homepage office preview",
  },
  {
    id: "waiting-room",
    file: "Waiting room.jpg",
    category: "Waiting area",
    alt: "View from the waiting room toward the reception counter and wall map",
    placement: "Alternate; wider waiting-room view selected",
  },
];
